### ISSUE TITLE
modification for code section

### ISSUE THREAD

**Issue by badar-chachar** [ksegla/GitHubMiner#1]
How can i modify this code to get a list of repositories for code section on github instead of repositories.

`https://github.com/search?q=%22smart+contract%22&type=code`

instead of 

`https://github.com/search?q=%22smart+contract%22&type=repositories`

**Comment by ksegla** [comment]
Hi

You cannot do that with the GitHub API. These are the only possibilities:

ISSUE
Returns results matching issues in repositories.

REPOSITORY
Returns results matching repositories.

USER
Returns results matching users and organizations on GitHub.

DISCUSSION
Returns matching discussions in repositories.

There is no CODE type. 

If you are trying to get gists, they are considered repositories so you can get them without changes.

**Comment by badar-chachar** [comment]
Hi @ksegla,
Thanks a lot for the response.
I was able to do it with [PyGithub](https://pygithub.readthedocs.io/en/latest/introduction.html) that uses Rest API. It has a function `search_code` that returns the results similar to that on the webpage in code section.

Thanks again.

**Comment by ksegla** [comment]
Hi @badar-chachar 
We will look into this for future iterations but most likely, we will stay within the capabilities of the GraphQL API. Let's hope it catches up soon with the REST API :)

**Comment by badar-chachar** [comment]
@ksegla sure. Thanks
